#!/bin/bash

echo "stop ntp..."

ssh shangdehaovm1 "service ntp stop"
ssh shangdehaovm2 "service ntp stop"
ssh shangdehaovm3 "service ntp stop"
ssh shangdehaovm4 "service ntp stop"
ssh shangdehaovm5 "service ntp stop"
ssh sdh2vm1 "service ntp stop"
ssh sdh2vm2 "service ntp stop"
ssh sdh4vm1 "service ntp stop"
ssh sdh4vm2 "service ntp stop"
ssh sdh4vm2 "service ntp stop"

ssh plana300.shangdehao.com "service ntp stop"
ssh plana301.shangdehao.com "service ntp stop"
ssh plana302.shangdehao.com "service ntp stop"
ssh plana303.shangdehao.com "service ntp stop"
ssh plana304.shangdehao.com "service ntp stop"
ssh plana305.shangdehao.com "service ntp stop"
ssh plana306.shangdehao.com "service ntp stop"
ssh plana307.shangdehao.com "service ntp stop"
ssh plana308.shangdehao.com "service ntp stop"


echo "\n ntpdate 10.239.48.148"
ssh shangdehaovm1 "timedatectl set-timezone Asia/Shanghai; ntpdate 10.239.48.148; service ntp start"
ssh shangdehaovm2 "timedatectl set-timezone Asia/Shanghai; ntpdate 10.239.48.148; service ntp start"
ssh shangdehaovm3 "timedatectl set-timezone Asia/Shanghai; ntpdate 10.239.48.148; service ntp start"
ssh shangdehaovm4 "timedatectl set-timezone Asia/Shanghai; ntpdate 10.239.48.148; service ntp start"
ssh shangdehaovm5 "timedatectl set-timezone Asia/Shanghai; ntpdate 10.239.48.148; service ntp start"
#ssh sdh2vm1 "timedatectl set-timezone Asia/Shanghai; ntpdate 10.239.48.148; service ntp start"
#ssh sdh2vm2 "timedatectl set-timezone Asia/Shanghai; ntpdate 10.239.48.148; service ntp start"
#ssh sdh4vm1 "timedatectl set-timezone Asia/Shanghai; ntpdate 10.239.48.148; service ntp start"
#ssh sdh4vm2 "timedatectl set-timezone Asia/Shanghai; ntpdate 10.239.48.148; service ntp start"


echo "check time..."
ssh shangdehaovm1 "timedatectl"
echo " "
ssh shangdehaovm2 "timedatectl"
echo " "
ssh shangdehaovm3 "timedatectl"
echo " "
ssh shangdehaovm4 "timedatectl"
echo " "
ssh shangdehaovm5 "timedatectl"
#echo " "
#ssh sdh2vm1 "timedatectl"
#echo " "
#ssh sdh2vm2 "timedatectl"
#echo " "
#ssh sdh4vm1 "timedatectl"
#echo " "
#ssh sdh4vm2 "timedatectl"
#
